### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by MrMoronIV** [flix-tech/schema-registry-php-client#33]
Say I have my schema registry endpoint protected using basic auth from Nginx. Would I be able to define the login details somewhere special or just in the url like this?:

```
https://username:password@registry.example.com/
```

**Comment by tPl0ch** [comment]
I believe the easiest way would be adding the auth info to the underlying Guzzle client: http://docs.guzzlephp.org/en/stable/request-options.html#auth
