### ISSUE TITLE
breaking changes / semver

### ISSUE THREAD

**Issue by rs-sliske** [flix-tech/schema-registry-php-client#52]
the recent 7.3.0 release made some breaking changes. (deleting / renaming of classes) 

im not actually requiring this project directly, but it is required by flix-tech/avro-serde-php with a version selector of ~7.1 which will select the latest version up until 8.0 gets released. 

if you dont want to follow semver then that is fine, but in that case you need to be more careful with required versions so that users of your (otherwise) great libraries dont have to deal with breaking changes

**Comment by tPl0ch** [comment]
@rs-sliske you are right, and I am deeply sorry about this. There should not have been a release 7.3.0 because some other breaking changes were released in master beforehand that should go into 8.0.

For now I recommend pinning the version to 7.2. Sorry for this.

**Comment by tPl0ch** [comment]
@rs-sliske I have reverted the changes and reapplied the PHP8 support. Version 7.3.1 should work as expected. Thanks for the report!
