### ISSUE TITLE
How to use with distributed schema registries?

### ISSUE THREAD

**Issue by marcverney** [flix-tech/schema-registry-php-client#74]
Hi. The  schema registry I need to connect to is distributed over three instances/hosts. Reading the documentation, I only find how to connect to a single instance:
```php
$registry = new PromisingRegistry(
    new Client(['base_uri' => 'registry.example.com'])
);
```
Can you tell me how I should use this library with distributed schema registries? (e.g. **registry1**.example.com, **registry2**.example.com and **registry3**.example.com)

**Comment by tPl0ch** [comment]
@marcverney You can easily achieve this by adding this functionality to the underlying Guzzle Client via a [custom handler](https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html).

**Comment by marcverney** [comment]
Thanks @tPl0ch. It looks like a quite advanced Guzzle functionality. Neither their documentation, nor Google makes it clear to me how to achieve this fallback mechanism. Could you give me a short code example (or point me at an existing one somewhere)?
